AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates Ec2 with security group and enables SSH.
Resources:
  myEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: keyname  # this is my keypair, use your own key file without extension.
      SecurityGroups:
        - SGname
      Tags:
        - Key: Name
          Value: CFInstance



